config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: 'users/registrations'}
  devise_for :admins, skip: [:registrations], controllers: {sessions: 'admins/sessions'}

  namespace :admin do 
    root to: "home#index"
    resources :admins
    resources :users, only: :index
    resources :posts, only: [:show, :index]
  end

  
  root to: "user/timeline#index"

  namespace :user do
     get 'profile', to: "profile#show"
     get 'potential_to_follow', to: "profile#potential_to_follow"
     get 'following', to: "profile#following"
     get 'followers', to: "profile#followers"
     resources :posts, only: :create

    #  post para seguidores
    post 'follow/:id', to: "subscriptions#follow", as: :follow
    #Deixar de seguir
    post 'unfollow/:id', to: "subscriptions#unfollow", as: :unfollow
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  validates :body, presence: true
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :followed, class_name: "User"
  belongs_to :followed_by, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable
  
  validates :phone, :name, :avatar,  presence: true
  
  has_one_attached :avatar

  has_many :posts, :dependent => :destroy
  #Seguidores Seguidos
  has_many :followers_subscriptions, foreign_key: :followed_id, class_name: "Subscription"
  has_many :followers, through: :followers_subscriptions, source: :followed_by
  
  #Seguidores que Seguem 
  has_many :following_subscriptions, foreign_key: :followed_by_id, class_name: "Subscription"
  has_many :following, through: :following_subscriptions, source: :followed

  #Cria parametro para indicar comando
  scope :potential_to_follow, -> (user) {where.not(id: user.following.pluck(:id)).where.not(id: user.id)}
end

app/controllers/admin/admins_controller.rb
class Admin::AdminsController < AdminController 
  before_action :set_admin, only: [:edit, :destroy, :update]

  def index 
    @admins = Admin.all.order(id: :desc)
  end

  def new 
    @admin = Admin.new
  end

  def create 
    @admin = Admin.new(form_params)
    if @admin.save
      redirect_to admin_admins_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit 

  end

  def update 
    params = form_params.to_h
    params = params.except!(:password, :password_confirmation) if params[:password].blank?

    if @admin.update(params)
      redirect_to admin_admins_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy 
    
    @admin.destroy
    redirect_to admin_admins_path
  end

  private 

  def form_params
    params.require(:admin).permit(:name,  :email,  :password, :password_confirmation)
  end

  def set_admin
    @admin = Admin.find(params[:id])
  end

end

app/controllers/admin/home_controller.rb
class Admin::HomeController < AdminController
  
  def index

  end
  
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < AdminController
  
  def index
    @posts = Post.all.order(created_at: :desc)
  end

  def show
     @post = Post.find(params[:id])
  end
  
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController

  def index
    @users = User.order(id: :desc)
  end

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_admin

  def authenticate_admin
    redirect_to new_admin_session_path unless current_admin
  end

  def current_admin?
    if current_admin.present?
      true
    else
      false
    end
  end


end

app/controllers/admins/sessions_controller.rb
class Admins::SessionsController < Devise::SessionsController 
  def after_sign_out_path_for(admin) 
    new_admin_session_path
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/user/posts_controller.rb
class User::PostsController < UserController

  def create

    f_params = form_params.merge(user: current_user)

    @post = Post.new(f_params)

    if @post.save
      redirect_to user_profile_path
    else
      render "user/profile/show" , status: :unprocessable_entity
    end

  end

private

  def form_params 
    params.require(:post).permit(:body)
  end

end

app/controllers/user/profile_controller.rb
class User::ProfileController < UserController

  def show
    @post = Post.new
  end

  def potential_to_follow
    @potential_to_follow = User.potential_to_follow(current_user)
  end

  def following
    @following = current_user.following
  end

  def followers
    @followers = current_user.followers
  end
  
end

app/controllers/user/subscriptions_controller.rb
class User::SubscriptionsController < UserController

  def follow
   user_to_follow = User.find_by(id: params[:id])
   Subscription.create(followed_by: current_user, followed: user_to_follow)

   redirect_to user_potential_to_follow_path
  end

  def following
    @potential_to_follow = User.where.not(id: current_user.following.pluck(:id)).where.not(id: current_user.id)
  end

  def unfollow
    user = User.find_by(id: params[:id])
    subscription = Subscription.find_by(followed_by: current_user, followed: user)
    subscription.destroy

    redirect_to user_following_path
  end
  
end

app/controllers/user/timeline_controller.rb
class User::TimelineController < UserController

  def index
    
  end
  
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_action :authenticate_user

  def authenticate_user
    redirect_to new_user_session_path unless current_user
  end



end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController <  Devise::RegistrationsController
  before_action :configure_sign_up_params

  protected
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:phone, :name, :avatar])
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/admins/_form.html.erb
<div class="card" style="background-color:#f6f6f6;">
  <div class="card-body ">
    <%= form_with(model: [:admin, admin], local: true) do |f| %>
      <%= render 'layouts/form_errors', record: admin %>
      <div class="form-group">
        <label for="formGroupExampleInput">Nome</label>
        <%= f.text_field :name, class:'form-control' %>
      </div>
      <div class="form-group">
        <label for="exampleInputEmail1">Email</label>
        <%= f.email_field :email, class:'form-control' %>
      </div>
      <div class="form-row">
        <div class="col-6">
          <div class="form-group">
            <label for="exampleInputPassword1">Senha</label>
            <%= f.password_field :password , class:'form-control' %>
          </div>
        </div>
        <div class="col-6">
          <div class="form-group">
            <label for="exampleInputPassword1">Confirmar Senha</label>
            <%= f.password_field :password_confirmation , class:'form-control' %>
          </div>
        </div>
      </div>      
      <%= f.submit 'Salvar', class:'btn btn-primary' %>
      <%= link_to 'Voltar', admin_admins_path, class:'btn btn-secondary' %>
    <% end %>
  </div>
</div>

app/views/admin/admins/edit.html.erb
<h2>Editar Administrador ID: <%= @admin.id %> </h2>
<%= render 'form', admin: @admin %>

app/views/admin/admins/index.html.erb
<h4>Admins</h4><br>
<%= link_to "Novo Administrador", new_admin_admin_path, class:'btn btn-primary mb-2'%>

<table class="table table-dark">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Nome</th>
      <th scope="col">E-mail</th>
      <th scope="col"></th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
  <% @admins.each do  |admin| %>
    <tr>
      <th scope="row"><%= admin.id %></th>
      <td><%= admin.name %></td>
      <td><%= admin.email %></td>
      <td><%= link_to 'Editar', edit_admin_admin_path(admin), class:'btn btn-warning btn-sm' %></td>
      <td><%= link_to 'Deletar', admin_admin_path(admin),  data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'}, class:'btn btn-danger btn-sm' %></td>
    </tr>
    <% end%>
  </tbody>
</table>

app/views/admin/admins/new.html.erb
<h2>Novo Administrador</h2>
<%= render 'form', admin: @admin %>

app/views/admin/home/index.html.erb
<p>ola<p/>

app/views/admin/posts/index.html.erb
<h4>Posts</h4>
<br>
<table class="table table-dark">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Photo</th>
      <th scope="col">Post</th>
      <th scope="col">Criado em</th>
    </tr>
  </thead>
  <tbody>
    <% @posts.each do  |post| %>
      <tr>
        <th scope="row"><%= post.id %></th>
        <td><%= image_tag(post.user.avatar, class:'ui-w-100-forced rounded-circle', style:'width: 30px; height: 30px;' ) %><small class="align-center"> <%= post.user.name %></small></td>
      </td>
      <td><%=link_to  post.body.truncate(30), admin_post_path(post) %></td>
      <td><%= post.created_at.strftime('%d/%m/%Y %H:%m') %></td>
    </tr>
  <% end%>
</tbody>
</table>

app/views/admin/posts/show.html.erb
<h4>Post # <%= @post.id %></h4>
<br>
<div class="card text-white bg-dark mb-3 mt-3">
  <div class="card-header text-center align-center ">
    <h5><%= @post.user.name %></h5>
    <small class=""><%= image_tag(@post.user.avatar, class:'ui-w-100-forced rounded-circle', style:'width: 30px; height: 30px;' ) %></small></div>
  <div class="card-body">
    <small class="text-muted"><%= @post.created_at.strftime("%d/%m/%Y %H:%M") %></small>
    <p class="card-text"><%= @post.body %></p>
  </div>
</div>

app/views/admin/users/index.html.erb
<h4>Usuários</h4><br>

<table class="table table-dark">
  <thead>
    <tr class="text-center">
      <th scope="col">#</th>
      <th scope="col">Photo</th>
      <th scope="col">Nome</th>
      <th scope="col">E-mail</th>
      <th scope="col">Telefone</th>
      <th scope="col">Seguindo</th>
      <th scope="col">Seguidores</th>
      <th scope="col">Created_at</th>
    </tr>
  </thead>
  <tbody>
  <% @users.each do  |user| %>
    <tr class="text-center">
      <th scope="row"><%= user.id %></th>
      <td><%= image_tag(user.avatar, class:'ui-w-100-forced rounded-circle', style:'width: 30px; height: 30px;' ) %></td>
      <td><%= user.name %></td>
      <td><%= user.email %></td>
      <td><%= user.phone %></td>
      <td><%= user.following.count %></td>
      <td><%= user.followers.count %></td>
      <td><%= user.created_at.strftime('%d/%m/%Y %H:%m') %></td>
    </tr>
    <% end%>
  </tbody>
</table>

app/views/layouts/_form_errors.html.erb
<% if record && record.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <h4 class="alert-heading"><%= t('.error_on_save') %></h4>
    <ul>
    <% record.errors.each do |message| %>
      <li><%= message.full_message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/admin.html.erb
<% content_for :content do %>
  <%= render "layouts/admin/header" %>
  <div class="container mt-5">
    <%= yield %>
  </div>
<% end %>


<%= render template: "layouts/application" %>

app/views/layouts/admin/_header.html.erb
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
  <div class="container">
    <ul class="navbar-nav">
      <li class="nav-item <%= current_page?(admin_root_path) ? "active" : ""%> ">
        <%= link_to 'Home', admin_root_url, class:'nav-link'%>
      </li>
      <li class="nav-item <%= current_page?(admin_admins_path) ? "active" : ""%> ">
        <%= link_to 'Administradores', admin_admins_path, class:'nav-link'%>
      </li>
      <li class="nav-item <%= current_page?(admin_users_path) ? "active" : ""%> ">
        <%= link_to 'Usuários', admin_users_path, class:'nav-link'%>
      </li>
     <li class="nav-item <%= current_page?(admin_posts_path) ? "active" : ""%> ">
        <%= link_to 'Posts', admin_posts_path, class:'nav-link'%>
      </li>
    </ul>
    <div class="nav-item d-flex">
      <ul class="navbar-nav">
        <li class="nav-item">
          <div class="py-2 mr-4" style="color:#fff;"><%= current_admin.email%></div>
        </li>
        <li class="nav-item">
          <%= link_to "Sair", destroy_admin_session_path, method:  :delete, class:'nav-link'%>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html style="height: 100%;" >
  <head>
    <title>Mask</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%# Custom %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <%# Custom %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body style="height: 100%;">
    <%= content_for?(:content) ? yield(:content) : yield %>
  </body>
</html>

app/views/layouts/user.html.erb
<% content_for :content do %>
  <%= render "layouts/user/header" %>
  <div class="container mt-5">
    <%= yield %>
  </div>
<% end %>

<%= render template: "layouts/application" %>

app/views/layouts/user/_header.html.erb
<nav class="navbar navbar-expand-sm bg-primary navbar-dark" style="background-color:#000080!important;">
  <div class="container" >
    <%= image_tag("logo.png", alt: "logo", class: 'navbar-brand', style: "height:40px;")%>
    <ul class="navbar-nav">
      <li class="nav-item <%= current_page?(root_path) ? "active" : "" %>">
        <%= link_to  "Timeline", root_path, class:'nav-link' %>
      </li>
      <li class="nav-item "<%= current_page?(user_followers_path)? "active" : "" %>">
        <%= link_to  "Followers", user_followers_path, class:'nav-link' %>
      </li>
      <li class="nav-item "<%= current_page?(user_following_path)? "active" : "" %>">
        <%= link_to  "Following", user_following_path, class:'nav-link' %>
      </li>
      <li class="nav-item "<%= current_page?(user_potential_to_follow_path)? "active" : "" %>">
        <%= link_to  "Quem eu posso seguir", user_potential_to_follow_path, class:'nav-link' %>
      </li>
      <li class="nav-item">
        <li class="nav-item "<%= current_page?(user_profile_path)? "active" : "" %>">
          <%= link_to  "Meu Perfil", user_profile_path, class:'nav-link' %>
        </li>
      </ul>
      <div class="nav-item d-flex">
        <ul class="navbar-nav">
          <li class="nav-item">
            <div class="py-2 mr-4" style="color:#fff;"><%= current_user.email%></div>
          </li>
          <li class="nav-item">
            <%= link_to "Sair", destroy_user_session_path, method:  :delete, class:'nav-link'%>
          </li>
        </ul>
      </div>
    </div>
  </nav>

app/views/user/profile/_user_card_header.html.erb
<h5 class="card-header"><%= image_tag(user.avatar, class:'ui-w-100-forced rounded-circle mr-3', style: 'width: 90px; height: 90px;') %>
  <%= user.name %>
</br>
<span style="font-size:14px;">Seguidores: <span style="font-size:16px;" class="badge badge-info mr-3"><%= user.followers.count %></span></span>
<span style="font-size:14px;">Seguindo: <span style="font-size:16px;" class="badge badge-info mr-3"><%= user.following.count %></span></span>
</h5>

app/views/user/profile/followers.html.erb
<div class="row">
  <% @followers.each do |user| %>
    <div class="col-lg-4">
      <div class="card">
        <%= render("user_card_header", user: user) %>
        <div class="card-body">
          Email:
          <p class="card-text text-muted"><%= user.email %></p>
          Telefone:
          <p class="card-text text-muted"><%= user.phone %></p>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/user/profile/following.html.erb
<div class="row">
  <% @following.each do |user| %>
    <div class="col-lg-4">
      <div class="card">
        <%= render("user_card_header", user: user) %>
        <div class="card-body">
          Email:
          <p class="card-text text-muted"><%= user.email %></p>
          Telefone:
          <p class="card-text text-muted"><%= user.phone %></p>
          <%= link_to("Deixar de Seguir", user_unfollow_path(user),  data: { 'turbo-method' => :post }, class:"btn btn-danger") %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/user/profile/potential_to_follow.html.erb
<div class="row">
  <% @potential_to_follow.each do |user| %>
    <div class="col-lg-4">
      <div class="card">
        <%= render("user_card_header", user: user) %>
        <div class="card-body">
          Email:
          <p class="card-text text-muted"><%= user.email %></p>
          Telefone:
          <p class="card-text text-muted"><%= user.phone %></p>
          <%= link_to("Seguir", user_follow_path(user),  data: { 'turbo-method' => :post }, class:"btn btn-success") %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/user/profile/show.html.erb
<div class="row">
  <div class="col-lg-6">
    <div class="card">
      <div class="card-body">
        <%= render("user_card_header", user: current_user) %>
        Email:
        <p class="card-text text-muted"><%= current_user.email %></p>
        Telefone:
        <p class="card-text text-muted"><%= current_user.phone %></p>
      </div>
    </div>
  </div>
  <div class="col-lg-6">
    <div class="card">
      <div class="card-body">
        <%= form_with(model: [:user, @post], local: true) do |f| %>
          <%= render("layouts/form_errors", record: @post) %>
          <div class="form-group">
            <label for="exampleInputEmail1">Post</label>
            <%= f.text_area :body, rows: 5,  class:'form-control', placeholder: 'Mande seu post...' %>
          </div>
          <button type="submit" class="btn btn-primary">Postar</button>
        <% end %>
      </div>
    </div>
    <% current_user.posts.order(created_at: :desc).each do |post| %>
      <div class="card text-white bg-dark mb-3 mt-3">
        <div class="card-header"><%= post.user.name %></div>
        <div class="card-body">
          <small class="text-muted"><%= post.created_at.strftime("%d/%m/%Y %H:%M") %></small>
          <p class="card-text"><%= post.body %></p>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/user/timeline/index.html.erb
<h2>Seja Bem vindo <%= current_user.name %><h2/>